### ISSUE TITLE
difference from baloon.css

### ISSUE THREAD

**Issue by matijakovacevic** [tiaanduplessis/wenk#27]
https://github.com/kazzkiq/balloon.css

how is this different from let's say, a similar project like baloon.css?
thank you

**Comment by tiaanduplessis** [comment]
@matijakovacevic both provide similar functionality. There are however some minor styling differences and wenk is a bit smaller as it doesn't provide styling for the tooltip arrow. The initial release of wenk was a couple of months prior to balloon.css, otherwise, I most likely wouldn't have written it 🤷‍♂️

**Comment by matijakovacevic** [comment]
thank you for the response
